

# \u6570\u636E\u5E93\u914D\u7F6E
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    username: project
    password: 37SpbDHwjThaWyM6
    url: jdbc:mysql://123.249.11.153:3306/project?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      #password:(未设置所以暂时先注释掉)
      lettuce:
        pool:
          max-active: 4
          max-idle: 4
          min-idle: 4
          max-wait: 1000ms
      timeout: 2000ms
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  # 上传文件大小配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# \u914D\u7F6Emybatis\u5B9E\u4F53\u548Cxml\u6620\u5C04
mybatis:
  ## \u6620\u5C04xml clssspath\u5BF9\u5E94resources
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #\u914D\u7F6E\u65E5\u5FD7
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


# alipay
alipay:
  easy:
    protocol: https
    gatewayHost: openapi-sandbox.dl.alipaydev.com
    signType: RSA2
    appId: 9021000145690101
    merchantPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCCKYfA44SxG6LKWmOEAxPyeNdfcUJVujuyubWupacA448nSMfpJyCqtLgx1nkJBtBHruFnuUt6ELTEV5hBry37UP+7DmEjeYBas9NFloQJ8W9ev4hBPcbWj99ZYEQ41gcAnhBg4pa3WPKW/rzeaCgdVlbjwdziGrDbW8bH6hlrM0nAYbDCojJBqtBYi7hLD2IbsSfr4mwfEPlrOndnNlaWF20j48H++MixJ62JlUaaxy485bvouxV7lksfdfOC6Zo2dJO3qtu0o19gfxBPoUTAfmlZMDKm/PEJ/4T46ymsrm6Hq16DSEWV6qGYNewLI4gcbxb/BSxC8sFCoKgfygoHAgMBAAECggEARGEG9TlRUy2ehsmXcBmh2AbNtlEstRaiGBFhtb9Gjbv+T3f3ta+dhLBt95ihezF+J7pipff9A8JVBLSzwwYBlP6HakBynY1N9dh0jCE3enXAuTjLnuKSW9O3VR+yl10wzo07M3q2DNoIj3SByiFTuZ3LBdmpbYryEDsVoZ6E/gBw6eutmS+ARaL1n2DsXkwWJtJ6Pelo945M8CTAtX1123IWSzCELOkw8sB4Fv/eWahrTvKWh5Vl1hd1KsDw8Y8GB/c7EjPlchOmwrjq1Qgyy7M82FDm+FRYBQX2OBaDVQE/Z41xQjkz0ljS4zZMOD1uUWr8f3LW1pbiGqa0IdB6AQKBgQDSZNfZPNk6ABiQEadUuokDl5P2G/GNqX4nBMm7czx/TWPEx6icYcZYGsa0TIt0pn8r/Ta+xD5xcFIXWaDAEZacdBVS4sTOT5MeLewwJ3U6aCopt3Td4AmG0hl0AqkzN+hmWWA+4xk6wFz26D6DTtdveEKFYdN/zkMuyiCSjjudBwKBgQCeYHqM6jWbl7+CdWe33h6M1ULsG66zVyzB3C9tsQ3qGqsfoAe6IwcL9kPdSr/5g91BmOdr4w/H1dbpd6Oq0yeOObgE4faVkgaav8F2gUXC62PWQgPoaLtsHJhoOcZblXLcn+crFDpFDQDT1AcWa2aOLUTvlPIJqGM35M7/8w/rAQKBgQCZEHKUghdLggxcq+s/0iGiMmGb2EKJHHlB69LUBAdMWkIuRE9fziZdrMVJILMIX6T/nM16Rg1jvCKNCFDRyzn2guGMlpw1uGDAwQonEl3P6z5ZcTWdwcNMiYepBdKRB6iU5YsG1XNicdZwbxAjuXU0jJpgrYYQYkAwRy8hUEcAewKBgEPyloFgdlFjwGkjH7V12VuIn2aW1dPhgbVGVx7TiGm4uVQfH1GPd5V9OU52pHhTR5i+FgNmbj3JE6QkjRZb8yuEvdtyao1vEeBQhprmCV0AClxBBFYwoMBYYFbO+rgOHTJkdBQ6YGmBk6pN3CCVQXGcIGg9Wb4k/TRcuSZ8TIcBAoGBAMBUVNxEl/XiVwBDsYxxbKcFpcz17re5udhar5cTabG+RFv7jPASah3yl87ra7Hd9kkzSyb6ZjHpCjxYapjeikjpVS/+OQDFMpLxTmv/gkxGgMOitEJQDv+N0ekCx8MIUxuNFeLhfiKvQ0aUIh0AJBlCnfE1vQjYYVpC5xr4Fin9
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgWD7+Nci4UkK8bqxtWrGEK+4/OkcnC4NsTwnkeznZ+k1b+f1lUDB7er9bw8Vup1QDgq4x1nFlzZbbjO6VSxdRX0nFQFLuzXobx6E1SiHAoHFq3f0pG2En0EtAZJKxnwI4fr6zUF/c+VYUBVqJ2SYU2RVJXwp1RdQDxQ/KShfhKueOOHHl09lO0dUoPMzdfBIsNu8g9iCua68rHL97XeS7NazqDiiMDOSbGtvMTi30tQz6UEmiQl92WF5GFp8rPT3sSkKTtx1kccEBk3OaZJWJ5lNLXQuR7BWwbUHFqD5zT40ZcA8+n+Q98Hu8+hfIkLdQH9IBbSYNVJ+pdluJ4UWbwIDAQAB
    notifyUrl: http://5pt7ch.natappfree.cc/notify




