# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    username: yihu_system_1
    password: ${DB_PASSWORD:} # 需要替换为实际的数据库密码
    url: jdbc:mysql://yihu.rwlb.rds.aliyuncs.com/yihu?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
  data:
    redis:
      host: r-2zepv1h8e52zfqg5gl.redis.rds.aliyuncs.com
      port: 6379
      password: ${REDIS_PASSWORD:} # 需要替换为实际的Redis密码
      lettuce:
        pool:
          max-active: 4
          max-idle: 4
          min-idle: 4
          max-wait: 1000ms
      timeout: 2000ms
      username: server
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  # 上传文件大小配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# alipay配置
alipay:
  easy:
    protocol: https
    gatewayHost: openapi-sandbox.dl.alipaydev.com
    signType: RSA2
    appId: 9021000145690101
    merchantPrivateKey: ${ALIPAY_MERCHANT_PRIVATE_KEY:} # 需要替换为实际的商户私钥
    alipayPublicKey: ${ALIPAY_PUBLIC_KEY:} # 需要替换为实际的支付宝公钥
    notifyUrl: http://59.110.19.72:8080/api/order/pay/notify

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-qingdao.aliyuncs.com
    bucket-name: yihutest01
    access-key-id: ${OSS_ACCESS_KEY_ID:} # 需要替换为实际的Access Key ID
    access-key-secret: ${OSS_ACCESS_KEY_SECRET:} # 需要替换为实际的Access Key Secret
