

# \u6570\u636E\u5E93\u914D\u7F6E
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/yihu?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai

# \u914D\u7F6Emybatis\u5B9E\u4F53\u548Cxml\u6620\u5C04
mybatis:
  ## \u6620\u5C04xml clssspath\u5BF9\u5E94resources
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #\u914D\u7F6E\u65E5\u5FD7
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true